vaccination changes and hic pdf"
itmedicity/inteliqo_V1 pull request #235
Opened 2023-09-22 09:56 UTC by AmalAnil97

vaccination changes and hic pdf"

2023-09-26 07:47 UTC, itmedicity requested changes

2023-09-26 07:47 UTC, itmedicity commented on src/views/EmployeeRecord/VacccinationInformation/Entrydetails.jsx
> +          <Heading title= {details?.third_dose_due_date ? formatWithSunday(details?.third_dose_due_date) : 'N/A'}/>
Change  the fun passing functionality

2023-09-26 07:47 UTC, itmedicity commented on src/views/EmployeeRecord/VacccinationInformation/FirstdoseNottaken.jsx
> +import { useCallback } from 'react'
remove the multiple import

2023-09-27 05:00 UTC, AmalAnil97 commented on src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/VaccinationInformation/VaccinationInformation.jsx
> +          <CssVarsProvider>
correct

2023-09-27 05:00 UTC, AmalAnil97 commented on src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/VaccinationInformation/VaccinationInformation.jsx
> +                <CssVarsProvider>
new component added

2023-09-27 05:00 UTC, AmalAnil97 commented on src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/VaccinationInformation/VaccinationInformation.jsx
> +  const [vaccinationList, setVaccinationList] = useSelector(
changed

2023-09-27 05:00 UTC, AmalAnil97 commented on src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/VaccinationInformation/VaccinationInformation.jsx
> +                    {vaccinationList.second_dose_due_date === null
resolved

2023-09-27 05:01 UTC, AmalAnil97 commented on src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/VaccinationInformation/Previousvacc.jsx
> +              {item?.firstdose_date === null ? 'not required' : item.firstdose_date}
added ?

2023-09-27 05:01 UTC, AmalAnil97 commented on src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/VaccinationInformation/Previousvacc.jsx
> +              {item?.third_dose_given_date === null ? 'not required' : item.third_dose_given_date}
added

2023-09-27 05:01 UTC, AmalAnil97 commented on src/views/EmployeeRecord/VacccinationInformation/Entrydetails.jsx
> +          <Heading title= {details?.third_dose_due_date ? formatWithSunday(details?.third_dose_due_date) : 'N/A'}/>
changed

2023-09-27 05:02 UTC, AmalAnil97 commented on src/views/EmployeeRecord/VacccinationInformation/FirstdoseNottaken.jsx
> +import { useCallback } from 'react'
changed the multiple import

2023-09-27 05:03 UTC, itmedicity approved these changes

2023-09-27 05:04 UTC, merged